name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: 0 0 * * 5

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git $HOME/asdf --branch v0.8.0
      - name: Test the plugin
        run: |
          . $HOME/asdf/asdf.sh
          GITHUB_API_TOKEN=${{secrets.GITHUB_TOKEN}} asdf plugin-test mkcert $GITHUB_WORKSPACE 'mkcert --version' --asdf-tool-version ${{matrix.version}} --asdf-plugin-gitref $GITHUB_SHA
